#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc rule -a Emacs state=tiled

#bspc config borderless_monocle    true
#bspc config gapless_monocle       true
#bspc config focus_follows_pointer true
#bspc config paddingless_monocle   true
bspc config single_monocle        false

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch polybar
#polybar top -c ~/.config/polybar/config-top.ini &

