call plug#begin()

" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline'

call plug#end()

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = 'nord'

colorscheme nord
